server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
mybatis:
  mapper-locations: mybatis/*-mapper.xml
  configuration:
    map-underscore-to-camel-case: true